---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: strimzi-cluster-operator
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tfc-operator-hcp-terraform-operator
  namespace: tfc-operator-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tfc-operator-hcp-terraform-operator
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: keda-admission-webhooks
  namespace: keda
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keda-admission-webhooks
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: keda-operator
  namespace: keda
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keda-operator
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: keda-operator-metrics-apiserver
  namespace: keda
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keda-operator-metrics-apiserver
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
