---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmagent-vmks-victoria-metrics-k8s-stack
  namespace: vmks
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmagent-vmks-victoria-metrics-k8s-stack
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmalert-vmks-victoria-metrics-k8s-stack
  namespace: vmks
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmalert-vmks-victoria-metrics-k8s-stack
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmalertmanager-vmks-victoria-metrics-k8s-stack
  namespace: vmks
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vmalertmanager-vmks-victoria-metrics-k8s-stack
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
