---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kafbat-ui
  namespace: kafka
spec:
  hostnames:
    - kafka.wcloud.sh
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
      namespace: kgateway-system
      sectionName: https
  rules:
    - backendRefs:
        - name: kafbat-ui-kafka-ui
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
